import { useState } from 'react';
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom';
import { ArrowRight, ChevronDown, AtSign, Mail, Menu, Shield, Sparkles, Heart, X } from 'lucide-react';

const A='/assets/';
const assets={
  logo:A+'whc-logo-BlKGI4lr.jpeg', hero:A+'hero-DY-UMjhH.jpeg', founder:A+'founder-9zRdDk_D.png',
  outreach:A+'program-outreach-visits-DBM6L7lZ.jpg', advocacy:A+'program-advocacy-campaigns-BQGCTXKP.jpg', youth:A+'program-youth-mentorship-BExEtnuc.jpg'
};
const programs=[
  {slug:'healing-circles',title:'Healing Circles',body:'Confidential spaces where women can breathe, be heard and begin again.',image:assets.hero,icon:Heart,format:'Small-group sessions, online and in person',impact:'180+ circles held'},
  {slug:'community-outreach',title:'Community Outreach',body:'Consistent presence and practical support for women and children in our communities.',image:assets.outreach,icon:Shield,format:'Visits, care packages and follow-up support',impact:'3,500+ volunteer hours'},
  {slug:'advocacy-campaigns',title:'Advocacy Campaigns',body:'Public awareness on gender-based violence and child marriage — from streets to policy tables.',image:assets.advocacy,icon:Sparkles,format:'Community workshops, marches and policy briefings',impact:'3 states reached in first campaign'},
  {slug:'youth-mentorship',title:'Youth Mentorship',body:'Helping girls stay in school, grow in confidence and imagine a safer future.',image:assets.youth,icon:Heart,format:'Mentorship, skills and safety education',impact:'Young women supported across Nigeria'}
];
const nav=[['/','Home'],['/about','About'],['/programs','Programs'],['/blog','Blog'],['/gallery','Gallery'],['/support','Support & Safety'],['/contact','Contact']];

function Header(){const [open,setOpen]=useState(false); return <header className="site-header"><div className="container nav-wrap"><Link to="/" className="brand" onClick={()=>setOpen(false)}><img src={assets.logo} alt="The Women's Healing Circle"/><span>Women's Healing <b>Circle</b></span></Link><nav className={open?'mobile-nav open':'desktop-nav'}>{nav.map(([to,label])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}>{label}</NavLink>)}<Link className="button small" to="/get-involved" onClick={()=>setOpen(false)}>Get involved</Link></nav><button className="menu-btn" aria-label="Toggle menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>}
function Footer(){return <footer><div className="container footer-grid"><div className="footer-brand"><div className="script">The Women's <b>Healing Circle</b></div><p>A global sisterhood for women's rights, mental wellness and healing — rooted in Nigeria, reaching across borders.</p><div className="social"><a href="mailto:hello@womenshealingcircle.org"><Mail size={17}/></a><a href="https://instagram.com" aria-label="Instagram"><AtSign size={17}/></a></div></div><div><h4>Explore</h4>{nav.slice(1,5).map(([to,label])=><Link key={to} to={to}>{label}</Link>)}</div><div><h4>Connect</h4><Link to="/get-involved">Volunteer</Link><Link to="/support">Support the work</Link><Link to="/contact">Partner with us</Link></div></div><div className="container copyright"><span>© {new Date().getFullYear()} The Women's Healing Circle Foundation.</span><span>Made with care in Nigeria.</span></div></footer>}
function Layout(){return <><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/programs" element={<Programs/>}/><Route path="/programs/:slug" element={<ProgramDetail/>}/><Route path="/blog" element={<Blog/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/support" element={<Support/>}/><Route path="/contact" element={<Contact/>}/><Route path="/get-involved" element={<GetInvolved/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></>}
function PageHero({eyebrow,title,children}){return <section className="page-hero"><div className="container narrow center"><span className="eyebrow">{eyebrow}</span><h1 className="script">{title}</h1>{children&&<p>{children}</p>}</div></section>}
function Home(){return <><section className="hero"><div className="hero-image" style={{backgroundImage:`linear-gradient(90deg,rgba(34,25,31,.84),rgba(34,25,31,.23)),url(${assets.hero})`}}/><div className="container hero-content"><span className="eyebrow light">Healing · Advocacy · Sisterhood</span><h1 className="script">A softer place<br/>to become whole.</h1><p>A global women's rights and mental wellness foundation offering healing circles, outreach and advocacy — rooted in Nigeria.</p><div className="actions"><Link className="button" to="/get-involved">Find your circle <ArrowRight size={17}/></Link><Link className="text-link light" to="/about">Our story <ArrowRight size={16}/></Link></div></div></section><section className="section intro"><div className="container split"><div><span className="eyebrow">Why we exist</span><h2>Every woman deserves a safe place to land.</h2></div><div><p className="lead">The Women's Healing Circle is a global sisterhood for women navigating grief, violence, transition and hope.</p><p>We create the spaces, relationships and resources that help women heal — and then help one another rise.</p><Link className="text-link" to="/about">Meet the circle <ArrowRight size={16}/></Link></div></div></section><section className="section tinted"><div className="container"><SectionHeading eyebrow="What we do" title="Healing is personal. Change is collective."/><div className="cards three">{programs.slice(0,3).map(p=><ProgramCard key={p.slug} program={p}/>)}</div></div></section><Impact/><section className="section cta"><div className="container narrow center"><span className="eyebrow">You don't have to do this alone</span><h2>There is room for you here.</h2><p>Whether you need support, want to volunteer or can help fund the work, your next step matters.</p><Link className="button" to="/get-involved">Take your next step <ArrowRight size={17}/></Link></div></section></>}
function SectionHeading({eyebrow,title}){return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>}
function ProgramCard({program:p}){const Icon=p.icon; return <article className="program-card"><img src={p.image} alt={p.title}/><div className="card-body"><Icon size={22} className="icon"/><h3>{p.title}</h3><p>{p.body}</p><Link className="text-link" to={'/programs/'+p.slug}>Explore <ArrowRight size={15}/></Link></div></article>}
function Impact(){return <section className="impact"><div className="container stats">{[['12,000+','Women reached'],['180+','Healing circles'],['9','Countries'],['3,500+','Volunteer hours']].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>}
function About(){return <><PageHero eyebrow="Our story" title="A circle built on care.">We believe healing is a right, not a luxury — and that no woman should have to find her way back alone.</PageHero><section className="section"><div className="container split align-center"><img className="portrait" src={assets.founder} alt="Founder of The Women's Healing Circle"/><div><span className="eyebrow">The beginning</span><h2>Twelve women. One candle. A promise.</h2><p>WHC began in a living room in Lagos, where twelve women gathered for the first healing circle. What started as a quiet promise of confidentiality grew into a movement reaching women across Nigeria and beyond.</p><p>Today, our work is still rooted in presence: listening without judgment, returning when things are difficult and making space for every woman to become whole.</p><Link className="button" to="/programs">See our work <ArrowRight size={17}/></Link></div></div></section><section className="section tinted"><div className="container"><SectionHeading eyebrow="Our values" title="How we show up"/><div className="values"><div><Heart/><h3>Compassion without judgment</h3><p>Every story is welcome. Every woman is worthy of care.</p></div><div><Shield/><h3>Safety and confidentiality</h3><p>Trust is the first thing we protect in every circle and conversation.</p></div><div><Sparkles/><h3>Courage in advocacy</h3><p>We speak plainly about the systems that harm women and girls.</p></div></div></div></section></>}
function Programs(){return <><PageHero eyebrow="Our programs" title="Many doors into healing.">From private circles to public advocacy, each program is designed around dignity, safety and sustained relationship.</PageHero><section className="section"><div className="container cards two">{programs.map(p=><ProgramCard key={p.slug} program={p}/>)}</div></section><Impact/></>}
function ProgramDetail(){const {pathname}=useLocation(); const p=programs.find(x=>pathname.endsWith(x.slug))||programs[0]; return <><PageHero eyebrow="Program" title={p.title}>{p.body}</PageHero><section className="section"><div className="container detail split"><img src={p.image} alt={p.title}/><div><span className="eyebrow">What to expect</span><h2>A steady place to begin.</h2><p>{p.format}. We move at your pace, with care and practical follow-through.</p><div className="highlight"><strong>{p.impact}</strong><span>and growing with every circle</span></div><Link className="button" to="/get-involved">Get involved <ArrowRight size={17}/></Link></div></div></section></>}
function Blog(){return <><PageHero eyebrow="From the circle" title="Stories, practices and hope.">Reflections on healing, advocacy and the everyday courage of women.</PageHero><section className="section"><div className="container cards three">{[['Healing','Why circles matter: a practice of being witnessed','The work of healing begins when we know we do not have to perform our pain.'],['Advocacy','Safety is a community practice','Building safer futures for girls starts with the conversations we choose to have now.'],['Community updates','Presence over perfection','What it means to return, again and again, until presence becomes relationship.']].map(([tag,title,body])=><article className="post" key={title}><span className="eyebrow">{tag}</span><h3>{title}</h3><p>{body}</p><a className="text-link" href="#read">Read reflection <ArrowRight size={15}/></a></article>)}</div></section></>}
function Gallery(){return <><PageHero eyebrow="The circle in motion" title="A gallery of becoming.">Moments from our circles, outreach visits and community work.</PageHero><section className="section"><div className="container gallery">{[assets.hero,assets.outreach,assets.advocacy,assets.youth,assets.founder].map((img,i)=><img key={img} src={img} alt={['Healing circle','Community outreach','Advocacy campaign','Youth mentorship','Our founder'][i]}/>)}</div></section></>}
function Support(){const faqs=[['Is the circle confidential?','Yes. What is shared in a circle stays in the circle. We protect trust as the foundation of every gathering.'],['How do I join a circle?','Use the Get Involved page to send an interest form. Our team will share the next available circle and what to expect.'],['Is there a cost?','No. Healing circles, outreach support and mentorship programs are free and funded by donors and partners.'],['How is support used?','Gifts help fund facilitators, community visits, care resources, advocacy and youth mentorship.']]; return <><PageHero eyebrow="Support & safety" title="Care with clarity.">Your safety, privacy and dignity are central to everything we do.</PageHero><section className="section"><div className="container narrow"><SectionHeading eyebrow="Questions about giving and joining" title="A few things people ask"/>{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></section><section className="section tinted"><div className="container narrow center"><span className="eyebrow">Need immediate help?</span><h2>You deserve support right now.</h2><p>If you are in immediate danger, contact your local emergency service or a trusted person who can be with you. WHC is not an emergency response service.</p><Link className="button" to="/contact">Contact the team</Link></div></section></>}
function Form({kind='contact'}){const [sent,setSent]=useState(false); if(sent)return <div className="success"><h3>Thank you for reaching out.</h3><p>Your message has been captured locally for this demo. Connect your preferred form/email provider before launch to receive submissions.</p></div>; return <form onSubmit={e=>{e.preventDefault();setSent(true)}} className="form"><label>Name<input required name="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" placeholder="you@example.com"/></label>{kind==='contact'&&<label>How can we help?<select name="topic"><option>General enquiry</option><option>Join a circle</option><option>Volunteer</option><option>Partner with WHC</option></select></label>}<label>Message<textarea required name="message" rows="5" placeholder="Tell us a little more..."/></label><button className="button" type="submit">Send message <ArrowRight size={17}/></button></form>}
function Contact(){return <><PageHero eyebrow="Get in touch" title="We'd love to hear from you.">General enquiries, media requests, partnerships and questions about joining a circle.</PageHero><section className="section"><div className="container split"><div><span className="eyebrow">The door is open</span><h2>Start a conversation.</h2><p>Tell us what you need, what you are building or how you would like to stand with the sisterhood.</p><p><a className="text-link" href="mailto:hello@womenshealingcircle.org">hello@womenshealingcircle.org <ArrowRight size={15}/></a></p></div><Form/></div></section></>}
function GetInvolved(){return <><PageHero eyebrow="Find your place" title="There is room for you here.">Join a healing circle, volunteer your skills or help make this work possible.</PageHero><section className="section"><div className="container split"><div><span className="eyebrow">Get involved</span><h2>Choose your next step.</h2><p>We welcome women, allies, organizations, schools and faith communities who want to contribute to safer, more compassionate futures.</p><ul className="check-list"><li>Join a circle</li><li>Volunteer with outreach and advocacy</li><li>Partner or support the work</li></ul></div><Form kind="involvement"/></div></section></>}
function NotFound(){return <PageHero eyebrow="404" title="This page is still becoming."><Link className="button" to="/">Return home</Link></PageHero>}
export default function App(){return <BrowserRouter><Layout/></BrowserRouter>}
